# Makefile for FLP 2023/2024 project in Haskell language 
# Zaneta Grossová (xgross11)
# 31.3.2024

.PHONY: all clean

all:
	ghc -Wall -o ./flp-fun ./Main.hs ./Helper.hs ./Classification.hs ./TreeTraining.hs  ./DecisionTree.hs

clean:
	rm -f flp-fun
